// created by liuhan on 2023/9/15
// Submodule of HeliosRobotSystem
// for more see document: https://swjtuhelios.feishu.cn/docx/MfCsdfRxkoYk3oxWaazcfUpTnih?from=from_copylink
#pragma once

#include "helios_rs_interfaces/msg/target.hpp"
#include "sensor_msgs/msg/camera_info.hpp"

// auto generated by ros2 generate_parameter_library
// https://github.com/PickNikRobotics/generate_parameter_library
#include "helios_autoaim_parameters.hpp"

namespace helios_cv {

class BasePredictor {
public:
    BasePredictor() = default;

    virtual void set_cam_info(sensor_msgs::msg::CameraInfo::SharedPtr cam_info) = 0;

    virtual void init_predictor(helios_autoaim::Params::Predictor predictor_param) = 0;

    virtual helios_rs_interfaces::msg::Target predict_target() = 0;

    virtual void set_params(helios_autoaim::Params::Predictor predictor_params) = 0;
private:
};

} // namespace helios_cv