// created by liuhan on 2023/9/15
// Submodule of HeliosRobotSystem
// for more see document: https://swjtuhelios.feishu.cn/docx/MfCsdfRxkoYk3oxWaazcfUpTnih?from=from_copylink
#pragma once

#include "BasePredictor.hpp"

// auto generated by ros2 generate_parameter_library
// https://github.com/PickNikRobotics/generate_parameter_library
#include "helios_autoaim_parameters.hpp"

namespace helios_cv {

class EnergyPredictor : public BasePredictor {
public:
    EnergyPredictor(helios_autoaim::Params::Predictor::EnergyPredictor predictor_params);
    
    void set_cam_info(sensor_msgs::msg::CameraInfo::SharedPtr cam_info) override;

    void init_predictor(helios_autoaim::Params::Predictor predictor_param) override;

    helios_rs_interfaces::msg::Target predict_target() override;

    void set_params(helios_autoaim::Params::Predictor predictor_params) override;
private:

};


} // namespace helios_cv