// Copyright 2022 Chen Jun
// Licensed under the MIT License.

#ifndef ARMOR_DETECTOR__PNP_SOLVER_HPP_
#define ARMOR_DETECTOR__PNP_SOLVER_HPP_

#include <geometry_msgs/msg/point.hpp>
#include <helios_rs_interfaces/msg/detail/armor__struct.hpp>
#include <opencv2/core.hpp>

// STL
#include <array>
#include <vector>

#include "Armor.hpp"

// auto generated by ros2 generate_parameter_library
// https://github.com/PickNikRobotics/generate_parameter_library
#include "helios_autoaim_parameters.hpp"

namespace helios_cv {


class PnPSolver
{
public:
  PnPSolver(
    const std::array<double, 9> & camera_matrix,
    const std::vector<double> & distortion_coefficients,
    helios_autoaim::Params::PnpSolver pnp_solver_params);

  // Get 3d position
  bool solvePnP(const Armor & armor, cv::Mat & rvec, cv::Mat & tvec);

  // Calculate the distance between armor center and image center
  float calculateDistanceToCenter(const cv::Point2f & image_point);

private:
  cv::Mat camera_matrix_;
  cv::Mat dist_coeffs_;
  
  helios_autoaim::Params::PnpSolver pnp_solver_params_;

  // Four vertices of armor in 3d
  std::vector<cv::Point3f> small_armor_points_;
  std::vector<cv::Point3f> large_armor_points_;
  std::vector<cv::Point3f> energy_armor_points_;
};
} // namespace helios_cv

#endif  // ARMOR_DETECTOR__PNP_SOLVER_HPP_
