// created by liuhan on 2023/9/15
// Submodule of HeliosRobotSystem
// for more see document: https://swjtuhelios.feishu.cn/docx/MfCsdfRxkoYk3oxWaazcfUpTnih?from=from_copylink
#pragma once

#include "rclcpp/rclcpp.hpp"
#include "sensor_msgs/msg/camera_info.hpp"
#include "sensor_msgs/msg/image.hpp"
#include "helios_rs_interfaces/msg/armors.hpp"

#include "opencv2/core.hpp"
#include <geometry_msgs/msg/detail/pose__struct.hpp>
#include <opencv2/core/mat.hpp>

// auto generated by ros2 generate_parameter_library
// https://github.com/PickNikRobotics/generate_parameter_library
#include "helios_autoaim_parameters.hpp"

#include <vector>
namespace helios_cv {

class BaseDetector {
public:
    BaseDetector();

    virtual void set_cam_info(sensor_msgs::msg::CameraInfo::SharedPtr cam_info) = 0;

    virtual bool init_detector(helios_autoaim::Params::Detector detector_param) = 0;

    virtual helios_rs_interfaces::msg::Armors detect_targets(sensor_msgs::msg::Image::SharedPtr images) = 0;

    virtual cv::Mat& draw_results() = 0;

    virtual void set_params(helios_autoaim::Params::Detector detector_param) = 0;

    ~BaseDetector();
};

} // namespace helios_cv