// created by liuhan on 2023/9/15
// Submodule of HeliosRobotSystem
// for more see document: https://swjtuhelios.feishu.cn/docx/MfCsdfRxkoYk3oxWaazcfUpTnih?from=from_copylink
#pragma once

#include "BaseDetector.hpp"

// auto generated by ros2 generate_parameter_library
// https://github.com/PickNikRobotics/generate_parameter_library
#include "helios_autoaim_parameters.hpp"
namespace helios_cv {

class TraditionalEnergyDetector : public BaseDetector {
public:
    TraditionalEnergyDetector(helios_autoaim::Params::Detector::EnergyDetector detector_params);

    void set_cam_info(sensor_msgs::msg::CameraInfo::SharedPtr cam_info) override;

    bool init_detector(helios_autoaim::Params::Detector detector_param) override;

    helios_rs_interfaces::msg::Armors detect_targets(sensor_msgs::msg::Image::SharedPtr images) override;

    cv::Mat& draw_results() override;

    void set_params(helios_autoaim::Params::Detector detector_params) override;
private:
    helios_autoaim::Params::Detector::EnergyDetector detector_params_;
};

} // namespace helios_cv