// created by liuhan on 2023/9/15
// Submodule of HeliosRobotSystem
// for more see document: https://swjtuhelios.feishu.cn/docx/MfCsdfRxkoYk3oxWaazcfUpTnih?from=from_copylink
#pragma once

#include "BaseDetector.hpp"

#include <opencv2/core/mat.hpp>
#include <rclcpp/rclcpp.hpp>
#include <cv_bridge/cv_bridge.h>

#include <sensor_msgs/msg/camera_info.hpp>

#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/highgui.hpp>

#include <tf2/LinearMath/Matrix3x3.h>
#include <tf2_geometry_msgs/tf2_geometry_msgs.hpp>
#include <tf2/convert.h>


#include "Armor.hpp"
#include "NumberClassifier.hpp"
#include "PnPSolver.hpp"

// auto generated by ros2 generate_parameter_library
// https://github.com/PickNikRobotics/generate_parameter_library
#include "helios_autoaim_parameters.hpp"

namespace helios_cv {

class TraditionalArmorDetector : public BaseDetector {
public:
    TraditionalArmorDetector(std::shared_ptr<helios_autoaim::Params> params);

    void set_cam_info(sensor_msgs::msg::CameraInfo::SharedPtr cam_info) override;

    bool init_detector(std::shared_ptr<helios_autoaim::Params> params) override;

    helios_rs_interfaces::msg::Armors detect_targets(const cv::Mat& images) override;

    void draw_results(cv::Mat& img) override;

    void set_params(std::shared_ptr<helios_autoaim::Params> params) override;

private:

    cv::Mat preprocessImage(const cv::Mat & input);

    std::vector<Light> findLights(const cv::Mat & rbg_img, const cv::Mat & binary_img);
    
    std::vector<Armor> matchLights(const std::vector<Light> & lights);

    bool isLight(const Light & possible_light);
    
    bool containLight(
        const Light & light_1, const Light & light_2, const std::vector<Light> & lights);
    
    ArmorType isArmor(const Light & light_1, const Light & light_2);
    // submodules
    std::shared_ptr<PnPSolver> pnp_solver_;
    std::shared_ptr<NumberClassifier> number_classifier_;
    // params
    std::shared_ptr<helios_autoaim::Params> params_;
    // camera info
    cv::Point2f cam_center_;
    sensor_msgs::msg::CameraInfo::SharedPtr cam_info_;

    std::vector<Light> lights_;
    std::vector<Armor> armors_;
    helios_rs_interfaces::msg::Armors armors_interfaces_;
    // frame image
    cv::Mat frame_;
    cv::Mat binary_img_;

    void convert_armors_into_interfaces();

    rclcpp::Logger logger_ = rclcpp::get_logger("ArmorDetector");
};

} // namespace helios_cv