// created by liuhan on 2023/9/15
// Submodule of HeliosRobotSystem
// for more see document: https://swjtuhelios.feishu.cn/docx/MfCsdfRxkoYk3oxWaazcfUpTnih?from=from_copylink
#pragma once

#include "BaseDetector.hpp"

// auto generated by ros2 generate_parameter_library
// https://github.com/PickNikRobotics/generate_parameter_library
#include "helios_autoaim_parameters.hpp"

namespace helios_cv {

class TraditionalArmorDetector : public BaseDetector {
public:
    TraditionalArmorDetector(helios_autoaim::Params::Detector detector_params);
private:
    bool init_detector() override;

    bool detect_targets() override;

    void draw_results(cv::Mat& img) override;

    helios_autoaim::Params::Detector detector_params_;

    
};

} // namespace helios_cv