// created by liuhan on 2023/11/4
// Submodule of HeliosRobotSystem
// for more see document: https://swjtuhelios.feishu.cn/docx/MfCsdfRxkoYk3oxWaazcfUpTnih?from=from_copylink
/*
 * ██   ██ ███████ ██      ██  ██████  ███████
 * ██   ██ ██      ██      ██ ██    ██ ██
 * ███████ █████   ██      ██ ██    ██ ███████
 * ██   ██ ██      ██      ██ ██    ██      ██
 * ██   ██ ███████ ███████ ██  ██████  ███████
 */
#pragma once

#include <rclcpp/rclcpp.hpp>

#include "autoaim_interfaces/msg/target.hpp"
#include "autoaim_interfaces/msg/send_data.hpp"
#include "helios_control_interfaces/msg/shooter_cmd.hpp"
#include "helios_control_interfaces/msg/gimbal_cmd.hpp"


#include "TargetSolver.hpp"
#include "BulletSolver.hpp"

#include <Eigen/Core>
#include <Eigen/Dense>

// auto generated by ros2 generate_parameter_library
// https://github.com/PickNikRobotics/generate_parameter_library
#include "fire_controller_parameters.hpp"

namespace helios_cv {

using ParamListener = fire_controller::ParamListener;
using Params = fire_controller::Params;

class FireController : public rclcpp::Node {
public:
    FireController(const rclcpp::NodeOptions& options);

    ~FireController();
private:
    std::shared_ptr<ParamListener> param_listener_;
    Params params_;
    
    std::shared_ptr<BulletSolver> bullet_solver_;
    std::shared_ptr<TargetSolver> target_solver_;

    rclcpp::Subscription<autoaim_interfaces::msg::Target>::SharedPtr target_sub_;
    // rclcpp::Subscription<referee_interfaces::msg::BulletSpeed>::SharedPtr bullet_speed_sub_;
    // Here is compatibility with older EC codes
    rclcpp::Publisher<autoaim_interfaces::msg::SendData>::SharedPtr serial_pub_;
    rclcpp::Publisher<helios_control_interfaces::msg::GimbalCmd>::SharedPtr gimbal_pub_;
    rclcpp::Publisher<helios_control_interfaces::msg::ShooterCmd>::SharedPtr shoot_pub_;

    void target_callback(const autoaim_interfaces::msg::Target::SharedPtr target_msg);

    // void bullet_speed_callback();
    
    void target_process();

    autoaim_interfaces::msg::Target::SharedPtr target_msg_;

    rclcpp::Logger logger_ = rclcpp::get_logger("fire_controller");
};


} // namespace helios_cv